import { Button, LinkButton } from "@/components/Button"
import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.css"

const onClick = () => alert("click")

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Tests DSFR</h1>

        <p>
          <Button size="" disabled={false} onClick={onClick}>
            bouton par défaut
          </Button>
        </p>
        <p>
          <Button variant="secondary" size="sm" disabled={false} onClick={onClick}>
            bouton sm secondaire
          </Button>
        </p>
        <p>
          <Button variant="secondary" disabled={true} onClick={onClick}>
            bouton secondaire désactivé
          </Button>
        </p>
        <p>
          <Button variant="tertiary" size="sm" disabled={false} onClick={onClick}>
            bouton sm tertiaire
          </Button>
        </p>
        <p>
          <Button
            variant="tertiary-no-outline"
            size="sm"
            disabled={false}
            rightIcon="arrow-up-s-line"
            onClick={onClick}
          >
            bouton sm tertiaire no outline icone droite
          </Button>
        </p>
        <p>
          <Button variant="primary" size="lg" disabled={false} leftIcon="arrow-up-s-line" onClick={onClick}>
            bouton lg avec icone gauche
          </Button>
        </p>
        <p>
          <Button variant="secondary" size="sm" disabled={true} rightIcon="checkbox-circle-line" onClick={onClick}>
            bouton disabled avec icône droite
          </Button>
        </p>
        <p>
          <LinkButton variant="primary" size="lg" href="https://www.yahoo.fr">
            Link button lg
          </LinkButton>
        </p>
        <p>
          <LinkButton variant="secondary" size="sm" href="https://www.yahoo.fr">
            Link button secondary
          </LinkButton>
        </p>
        <p>
          <LinkButton variant="tertiary" size="sm" href="https://www.yahoo.fr">
            Link button tertiary
          </LinkButton>
        </p>
        <p>
          <LinkButton variant="tertiary-no-outline" size="sm" href="https://www.yahoo.fr">
            Link button tertiary no outline
          </LinkButton>
        </p>
        <p>
          <Button
            variant="primary"
            size="sm"
            disabled={false}
            onlyIcon="arrow-up-s-line"
            title="my dsfr button"
            onClick={onClick}
          ></Button>
          <span style={{ marginLeft: 5 }}>Bouton sans label</span>
        </p>
      </main>
    </div>
  )
}

export default Home
